In [81]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder


In [82]:
df=pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [83]:
df.shape

(569, 33)

In [84]:
df=df.drop(columns=['id','Unnamed: 32'])

In [85]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)
X_train.head(2)

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
73         13.80         15.79           90.43      584.1          0.10070   
437        14.04         15.98           89.78      611.2          0.08458   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
73            0.12800         0.07789              0.05069         0.1662   
437           0.05895         0.03534              0.02944         0.1714   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
73                  0.06566  ...         16.57          20.86   
437                 0.05898  ...         15.66          21.58   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
73             110.3       812.4            0.1411             0.3542   
437            101.2       750.0            0.1195             0.1252   

     concavity_worst  concave points_worst  symmetry_worst  \
73            0.2779               0.13830          0.2589   
437           0.1117               0.07453          0.2725   

     fractal_dimension_worst  
73                   0.10300  
437                  0.07234  

[2 rows x 30 columns]

In [86]:
y_train.head(2)

73     M
437    B
Name: diagnosis, dtype: object

In [87]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

X_train

array([[-0.09485945, -0.8058188 , -0.06495218, ...,  0.35952147,
        -0.51362968,  1.06875899],
       [-0.02827173, -0.7628522 , -0.0910909 , ..., -0.60132865,
        -0.29692514, -0.64550176],
       [-0.12815331, -0.6837032 , -0.17232199, ..., -0.41283508,
        -0.16785847, -0.3391042 ],
       ...,
       [-0.5803949 , -1.06814119, -0.56319639, ..., -0.73768891,
        -0.26187   , -0.04892112],
       [-0.68305096, -0.7198856 , -0.66574059, ..., -0.24543591,
        -0.1710453 , -0.20379726],
       [ 0.94279917, -0.00754463,  0.92711277, ...,  1.19727067,
         0.02653825, -0.29157904]], shape=(455, 30))

In [88]:
y_train

73     M
437    B
532    B
146    M
352    M
      ..
439    B
401    B
48     B
488    B
201    M
Name: diagnosis, Length: 455, dtype: object

In [89]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

y_train

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,

In [90]:
#Numpy arrays to tensors
X_train_tensor=torch.tensor(X_train)
X_test_tensor=torch.tensor(X_test)
y_train_tensor=torch.tensor(y_train)
y_test_tensor=torch.tensor(y_test)

In [91]:
X_train_tensor

tensor([[-0.0949, -0.8058, -0.0650,  ...,  0.3595, -0.5136,  1.0688],
        [-0.0283, -0.7629, -0.0911,  ..., -0.6013, -0.2969, -0.6455],
        [-0.1282, -0.6837, -0.1723,  ..., -0.4128, -0.1679, -0.3391],
        ...,
        [-0.5804, -1.0681, -0.5632,  ..., -0.7377, -0.2619, -0.0489],
        [-0.6831, -0.7199, -0.6657,  ..., -0.2454, -0.1710, -0.2038],
        [ 0.9428, -0.0075,  0.9271,  ...,  1.1973,  0.0265, -0.2916]],
       dtype=torch.float64)

In [92]:
#Defining The model

class MySimpleNN():
    def __init__(self,X):
        self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)

    def forward(self,X):
        z=torch.matmul(X,self.weights)+self.bias
        y_pred=torch.sigmoid(z)
        return y_pred
    
    def loss_function(self,y_pred,y_train_tensor):
        #Clamp prediction to avoid log(0) error
        epsilon=1e-7
        y_pred=torch.clamp(y_pred,epsilon,1-epsilon)

        #Calculate Loss
        loss=-(y_train_tensor*torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-y_pred)).mean()
        return loss
    
    
        

In [93]:
#important Parameters
learning_rate=0.1
epochs=25


In [94]:
#Training Pipeline
#Create Model
model=MySimpleNN(X_train_tensor)

#Training Loop
for epoch in   range(epochs):
    #forward Pass
    y_pred=model.forward(X_train_tensor)

    #Loss Function
    loss=model.loss_function(y_pred,y_train_tensor)
    # print(f'Epoch: {epoch+1} Loss: {loss}')

    #Backward Pass
    loss.backward()

    #parameter Update
    with torch.no_grad():
        model.weights-=learning_rate*model.weights.grad
        model.bias-=learning_rate*model.bias.grad

    #Zero the gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    print(f'Epoch: {epoch+1} Loss: {loss.item()}')

Epoch: 1 Loss: 3.2103759606908304
Epoch: 2 Loss: 3.076627580813155
Epoch: 3 Loss: 2.938082381495548
Epoch: 4 Loss: 2.7958881408435907
Epoch: 5 Loss: 2.649285653864149
Epoch: 6 Loss: 2.4998929078959087
Epoch: 7 Loss: 2.3503686791950007
Epoch: 8 Loss: 2.2036333968081308
Epoch: 9 Loss: 2.057069043203391
Epoch: 10 Loss: 1.9096374968917735
Epoch: 11 Loss: 1.7662884677973547
Epoch: 12 Loss: 1.625283410044044
Epoch: 13 Loss: 1.4928083619903123
Epoch: 14 Loss: 1.3697745523262366
Epoch: 15 Loss: 1.2576920302738508
Epoch: 16 Loss: 1.1611955782781986
Epoch: 17 Loss: 1.0808438345878333
Epoch: 18 Loss: 1.0161156250330687
Epoch: 19 Loss: 0.9653442979119089
Epoch: 20 Loss: 0.9260933837026015
Epoch: 21 Loss: 0.8957602621116081
Epoch: 22 Loss: 0.8720337121016409
Epoch: 23 Loss: 0.8530811686842743
Epoch: 24 Loss: 0.8375505172012992
Epoch: 25 Loss: 0.8244901966781961


In [95]:
model.bias

tensor([-0.1422], dtype=torch.float64, requires_grad=True)

In [96]:
with torch.no_grad():
    y_pred=model.forward(X_test_tensor)
    y_pred=torch.round(y_pred)
    accuracy=(y_pred==y_test_tensor).sum()/y_test_tensor.shape[0]
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 61.21052551269531
