In [86]:
import numpy as np
from sklearn.datasets import load_diabetes

X,y=load_diabetes(return_X_y=True)
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10))

In [87]:
X.shape

(442, 10)

In [88]:
y.shape

(442,)

In [89]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)


In [90]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(X,y)
y_pred=reg.predict(X_test)

from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.45729681888868934

In [91]:
reg.coef_,reg.intercept_

(array([ -10.0098663 , -239.81564367,  519.84592005,  324.3846455 ,
        -792.17563855,  476.73902101,  101.04326794,  177.06323767,
         751.27369956,   67.62669218]),
 np.float64(152.13348416289597))

In [92]:
#Making are own LinearRegression Class

class MeraLR:
    def __init__(self):
        self.coef_=None
        self.intercept_=None
    
    def fit(self,X_train,y_train):
        X_train=np.insert(X_train,0,1,axis=1)

        #calculate the coeffs
        betas=np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.intercept_=betas[0]
        self.coef_=betas[1:]

    def predict(self,X_test):
        y_pred=np.dot(X_test,self.coef_)+self.intercept_
        return y_pred


In [93]:
lr=MeraLR()

In [94]:
lr.fit(X_train,y_train)

In [95]:
y_pred=lr.predict(X_test)

In [96]:
r2_score(y_test,y_pred)

0.43993386615689756

In [98]:
lr.coef_,lr.intercept_

(array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
        -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
         861.12700152,   52.42112238]),
 np.float64(151.8833100525417))